
Ω
	cmd.protoprotocol*•
cmd
	HEARTBEAT
ECHO

LOGOUT
LOGIN_CHALLENGEd
LOGIN_EXCHANGEKEYe
LOGIN_HANDSHAKEf	
LOGINg
LOGIN_LAUNCHh
UPDATE_PLAYER_PROPERTYS»
GM_CHANGE_PLAYER_PROPERTY…
KICK_OUT_PLAYERÀ

LOAD_CARDSË
LOAD_CARD_DECKSÈ
UP_CARD_LEVELÍ

CHECK_CARDÎ
CHANGE_DECKÏ
CHANGE_CARD_DECKÌ
UPDATE_CARDSÓ
GM_GET_CARDÔ
MATCH_STARTêN
MATCH_CANCELëN
MATCH_UPDATEíN
BATTLE_INITìN
BATTLE_READYîN
BATTLE_STARTïN
BATTLE_ACTIONñN
BATTLE_FRAME_UPDATEóN

BATTLE_ENDòN