
½
	cmd.protoprotocol*¥
cmd
	HEARTBEAT
ECHO

LOGOUT
LOGIN_CHALLENGEd
LOGIN_EXCHANGEKEYe
LOGIN_HANDSHAKEf	
LOGINg
LOGIN_LAUNCHh
UPDATE_PLAYER_PROPERTYSÈ
GM_CHANGE_PLAYER_PROPERTYÉ
KICK_OUT_PLAYERË

LOAD_CARDSè
LOAD_CARD_DECKSé
UP_CARD_LEVELê

CHECK_CARDë
CHANGE_DECKì
CHANGE_CARD_DECKí
UPDATE_CARDSî
GM_GET_CARDï
MATCH_START°	
MATCH_CANCEL±	
MATCH_UPDATE²	
BATTLE_INIT³	
BATTLE_READY‘N
BATTLE_START’N
BATTLE_ACTION“N
BATTLE_FRAME_UPDATE”N

BATTLE_END•N